# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quadratic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fquadratic.proto\"H\n\x10QuadraticRequest\x12\x10\n\x08operandA\x18\x01 \x01(\x01\x12\x10\n\x08operandB\x18\x02 \x01(\x01\x12\x10\n\x08operandC\x18\x03 \x01(\x01\"\\\n\x11QuadraticResponse\x12\r\n\x05root1\x18\x01 \x01(\x01\x12\r\n\x05root2\x18\x02 \x01(\x01\x12)\n\x0fquadraticStatus\x18\x03 \x01(\x0e\x32\x10.QuadraticStatus*%\n\x0fQuadraticStatus\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\x41\n\tQuadratic\x12\x34\n\tCalculate\x12\x11.QuadraticRequest\x1a\x12.QuadraticResponse\"\x00\x62\x06proto3'
)

_QUADRATICSTATUS = _descriptor.EnumDescriptor(
  name='QuadraticStatus',
  full_name='QuadraticStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_QUADRATICSTATUS)

QuadraticStatus = enum_type_wrapper.EnumTypeWrapper(_QUADRATICSTATUS)
OK = 0
FAILED = 1



_QUADRATICREQUEST = _descriptor.Descriptor(
  name='QuadraticRequest',
  full_name='QuadraticRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operandA', full_name='QuadraticRequest.operandA', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operandB', full_name='QuadraticRequest.operandB', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operandC', full_name='QuadraticRequest.operandC', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=91,
)


_QUADRATICRESPONSE = _descriptor.Descriptor(
  name='QuadraticResponse',
  full_name='QuadraticResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='root1', full_name='QuadraticResponse.root1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root2', full_name='QuadraticResponse.root2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quadraticStatus', full_name='QuadraticResponse.quadraticStatus', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=185,
)

_QUADRATICRESPONSE.fields_by_name['quadraticStatus'].enum_type = _QUADRATICSTATUS
DESCRIPTOR.message_types_by_name['QuadraticRequest'] = _QUADRATICREQUEST
DESCRIPTOR.message_types_by_name['QuadraticResponse'] = _QUADRATICRESPONSE
DESCRIPTOR.enum_types_by_name['QuadraticStatus'] = _QUADRATICSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuadraticRequest = _reflection.GeneratedProtocolMessageType('QuadraticRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUADRATICREQUEST,
  '__module__' : 'quadratic_pb2'
  # @@protoc_insertion_point(class_scope:QuadraticRequest)
  })
_sym_db.RegisterMessage(QuadraticRequest)

QuadraticResponse = _reflection.GeneratedProtocolMessageType('QuadraticResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUADRATICRESPONSE,
  '__module__' : 'quadratic_pb2'
  # @@protoc_insertion_point(class_scope:QuadraticResponse)
  })
_sym_db.RegisterMessage(QuadraticResponse)



_QUADRATIC = _descriptor.ServiceDescriptor(
  name='Quadratic',
  full_name='Quadratic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='Quadratic.Calculate',
    index=0,
    containing_service=None,
    input_type=_QUADRATICREQUEST,
    output_type=_QUADRATICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUADRATIC)

DESCRIPTOR.services_by_name['Quadratic'] = _QUADRATIC

# @@protoc_insertion_point(module_scope)
